<?xml version="1.0"?>
<robot name="inspection_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Import base and camera macros -->
  <xacro:include filename="$(find robot_description)/urdf/robot_base.xacro"/>
  <xacro:include filename="$(find robot_description)/urdf/zed2i.xacro"/>

  <!-- Constants -->
  <xacro:property name="pi" value="3.14159"/>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${robot_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${robot_length} ${robot_width} ${robot_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.2 0.2 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${robot_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${robot_length} ${robot_width} ${robot_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="${chassis_mass}" x="${robot_length}" y="${robot_width}" z="${robot_height}"/>
  </link>

  <!-- Add left and right tracks -->
  <xacro:track prefix="left" reflect_y="1"/>
  <xacro:track prefix="right" reflect_y="-1"/>

  <!-- Add ZED2i camera -->
  <xacro:zed2i_camera name="zed2i" parent="base_link">
    <origin xyz="${robot_length/2 - 0.05} 0 ${robot_height + 0.05}" rpy="0 0 0"/>
  </xacro:zed2i_camera>

  <!-- Robot footprint for navigation -->
  <link name="base_footprint"/>
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${track_wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- IMU link -->
  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.01"/>
      </geometry>
      <material name="red">
        <color rgba="0.8 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${robot_height*0.8}" rpy="0 0 0"/>
  </joint>

  <!-- Gazebo plugins and configurations would go here for simulation -->

</robot>
