slam_toolbox:
  ros__parameters:
    # Robot frame settings
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping  # options: mapping, localization, slam

    # SLAM parameters
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 20.0
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 10.
    stack_size_to_use: 40000000
    enable_interactive_mode: false

    # Loop closure parameters
    loop_search_maximum_distance: 10.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_covariance: 3.0
    minimum_travel_heading: 0.5
    minimum_travel_distance: 1.0
    optimize_on_loop_detection: true
    loop_search_space_dimension: 4.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan matcher parameters
    matcher_type: 1  # CSM
    use_scan_matching: true
    ceres_loss_function: HuberLoss
    maximum_iterations: 50
