waypoints:
  # Sample inspection waypoints for a rectangular path around an airplane
  # These are in map frame coordinates and should be adjusted based on the actual airplane position
  - position:
      x: 5.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
    
  - position:
      x: 8.0
      y: 3.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.7071
      w: 0.7071  # 90 degrees rotation
    
  - position:
      x: 8.0
      y: 7.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 1.0
      w: 0.0  # 180 degrees rotation
      
  - position:
      x: 5.0 
      y: 10.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -0.7071
      w: 0.7071  # 270 degrees rotation
      
  - position:
      x: 0.0
      y: 7.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
      
  - position:
      x: 0.0
      y: 3.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.3826
      w: 0.9238  # 45 degrees rotation
      
  # Return to starting point
  - position:
      x: 5.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
